
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Panel
{
	public partial class WelcomePanel
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment topBarAlignment;

		private global::VAS.UI.Component.LicenseBannerView licenseBannerView;

		private global::Gtk.Button preferencesbutton;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.VBox vbox2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Panel.WelcomePanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Panel.WelcomePanel";
			// Container child LongoMatch.Gui.Panel.WelcomePanel.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 30;
			// Container child hbox1.Gtk.Box+BoxChild
			this.topBarAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.topBarAlignment.Name = "topBarAlignment";
			this.hbox1.Add (this.topBarAlignment);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.topBarAlignment]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.licenseBannerView = new global::VAS.UI.Component.LicenseBannerView ();
			this.licenseBannerView.Events = ((global::Gdk.EventMask)(256));
			this.licenseBannerView.Name = "licenseBannerView";
			this.hbox1.Add (this.licenseBannerView);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.licenseBannerView]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.preferencesbutton = new global::Gtk.Button ();
			this.preferencesbutton.Name = "preferencesbutton";
			this.hbox1.Add (this.preferencesbutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.preferencesbutton]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.alignment2.Add (this.vbox2);
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w6.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
